CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  VARCHAR(255)                                        NOT NULL,
    email VARCHAR(512) UNIQUE                                 NOT NULL
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    description  TEXT                                                NOT NULL,
    requestor_id BIGINT REFERENCES users (id)                        NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name         VARCHAR(255)                                        NOT NULL,
    description  VARCHAR(512)                                        NOT NULL,
    is_available BOOLEAN                                             NOT NULL,
    owner_id     BIGINT REFERENCES users (id)                        NOT NULL,
    request_id   BIGINT REFERENCES requests (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    item_id    BIGINT REFERENCES items (id)                        NOT NULL,
    booker_id  BIGINT REFERENCES users (id)                        NOT NULL,
    status     VARCHAR(8)                                          NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    text         TEXT                                                NOT NULL,
    item_id      BIGINT REFERENCES items (id)                        NOT NULL,
    author_id    BIGINT REFERENCES users (id)                        NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE                         NOT NULL
)